const data = {
	basic: {},
	content: {
		authModalCss: {
			bgColor: '#fafafa',
			borderColor: '#3749bb',
			btnFontSize: 16,
			btnFontWeight: 600,
			fgColor: '#353535',
			labelSize: 12,
			labelWeight: 600,
			primaryBtnBg: '#3749bb',
			primaryBtnFg: '#ffffff',
			primaryBtnHoverBg: '#253494',
			primaryBtnHoverFg: '#ffffff',
			secondaryBtnBg: '#ffffff',
			secondaryBtnFg: '#3749bb',
			secondaryBtnHoverBg: '#253494',
			secondaryBtnHoverFg: '#ffffff',
			secondaryTextColor: '#353535',
			secondaryTextSize: 12,
			titleAlign: 'center',
			titleColor: '#353535',
			titleFontWeight: 600,
			titleSizeBase: 14,
			titleSizeBg: 20,
			danger: '#ef4a23',
		},
	},
};
